# Generated by Django 3.2.7 on 2021-10-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjk', '0002_auto_20211024_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
