# Generated by Django 3.2.7 on 2021-11-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjk', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类啊', 'verbose_name_plural': '分类啊'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
